services:
  # Flask приложение для аналитики (порт 7777)
  push_analytic:
    build: .
    command: python run_app.py
    volumes:
      - .:/app
    environment:
      - FLASK_APP=src/api/notification_api.py
      - FLASK_ENV=${FLASK_ENV:-production}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGSSLMODE=${PGSSLMODE}
      - PGCHANNELBINDING=${PGCHANNELBINDING}
    ports:
      - "7777:5000"  # push_analytic на порту 7777
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/analytics/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - analytics-network

  # Nginx для аналитики
  push_analytic_nginx:
    image: nginx:1.25
    ports:
      - "7778:80"  # Nginx на порту 7778 для push_analytic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      push_analytic:
        condition: service_healthy
    networks:
      - analytics-network

networks:
  analytics-network:
    driver: bridge
